### ISSUE TITLE
Statistics on CGraph

### ISSUE THREAD

**Issue by danyaljj** [dykang/cgraph#1]
I am after of a few statistics to understand the graph structure of the knowledge graph in CGraph. 
Some I found from your paper.  I was wondering if you already have the remaining ones (or if there is an easy way to compute them)

Number of nodes:  5,623,924
Number of edges: 5,025,636 
Average node degree: 5,025,636 / (2 x 5,623,924) = 0.44 
Avg in-degree
Avg out-degree
Max in-degree
Max out-degree
Length of the longest path
The average length of paths
The median length of paths

**Comment by dykang** [comment]
I just saw this. Sorry for being late. I don't have the statistics yet but I will get them and make you posted.

**Comment by danyaljj** [comment]
Actually @dykang I collected the statistics on some other graphs. For now, I'm good. Thanks for the reply though! :)
